from __future__ import annotations


FILE_EXPLAINERS = {
    "live_motion_viewer": {
        "summary": "실시간 데모를 구동하는 메인 앱이다. static/runtime/tuning 설정을 읽고, 장비 제어 또는 raw replay 입력 선택, 워커 시작, UI 렌더링, SessionLogger 연계를 묶는다.",
        "mentor": "겉으로는 화면 파일처럼 보이지만 실제로는 앱 감독자다. live 입력일 때는 장비를 열고, replay 입력일 때는 저장된 raw capture를 불러오며, 최신 프레임만 골라 화면과 render/event 로그에 남긴다.",
        "read_order": [
            "MotionViewer.__init__에서 어떤 설정과 객체를 먼저 묶는지 본다.",
            "start_workers를 읽어 UdpListener, DataProcessor, MultiTargetTracker가 어떻게 연결되는지 본다.",
            "pull_latest_processed_frame와 update_figure를 읽어 왜 render 기준 로그와 processed 기준 로그가 나뉘는지 이해한다.",
        ],
        "landmarks": [
            ("MotionViewer", r"^class MotionViewer:", "앱의 메인 컨트롤러 클래스다."),
            ("runtime_summary", r"^\s*def runtime_summary", "현재 세션의 static/runtime/tuning 스냅샷을 로그에 남긴다."),
            ("log_render_snapshot", r"^\s*def log_render_snapshot", "실제로 그려진 프레임 기준 render 로그를 기록한다."),
            ("configure_dca1000", r"^\s*def configure_dca1000", "DCA1000 패킷/지연 설정을 하드웨어에 적용한다."),
            ("start_workers", r"^\s*def start_workers", "UDP 수신 스레드와 처리 스레드를 띄운다."),
            ("pull_latest_processed_frame", r"^\s*def pull_latest_processed_frame", "큐에서 최신 processed frame 하나만 꺼낸다."),
            ("update_figure", r"^\s*def update_figure", "최신 프레임을 받아 UI와 overlay를 갱신한다."),
            ("build_window", r"^\s*def build_window", "Qt 창과 2D/3D view를 조립한다."),
            ("shutdown", r"^\s*def shutdown", "장비, 워커, 로그 핸들을 정리한다."),
        ],
        "simple_model": "이 파일은 앱 감독이다. 센서 쪽과 알고리즘 쪽, 화면 쪽, 로그 쪽을 한 번에 지휘하면서 사용자가 보는 실시간 데모를 만든다.",
        "explainer_intro": "처음 볼 때는 UI 코드처럼 보이지만, 실제로는 어떤 설정으로 실험을 돌리고 어떤 프레임을 사용자에게 보여 줄지 결정하는 조정자다.",
        "explainer_steps": [
            {"title": "1. 세 층 설정을 읽는다", "summary": "앱 시작 시 static, runtime, tuning 설정을 읽고 Python 상수처럼 펼쳐 둔다.", "reason": "장비 설정과 실험 태그와 튜닝값을 한 번에 고정해야 세션 재현성이 생긴다.", "handoff": "runtime config 생성값, tracker/detection 파라미터, 로그 메타데이터"},
            {"title": "2. 앱 내부 객체를 묶는다", "summary": "Queue, DetectionRegion, SpatialViewController, SessionLogger를 만들고 MotionViewer 상태를 준비한다.", "reason": "실시간 파이프라인은 입력 큐, 처리 큐, 공간 ROI, 로그 경로가 모두 있어야 돌아간다.", "handoff": "raw_frame_queue, processed_frame_queue, detection_region, processed_log_path"},
            {"title": "3. 하드웨어와 워커를 연결한다", "summary": "configure_dca1000으로 DCA 설정을 적용하고 start_workers에서 UdpListener와 DataProcessor를 띄운다.", "reason": "센서 입력이 들어와도 처리 스레드가 없으면 화면과 로그로 이어지지 않는다.", "handoff": "실시간 FramePacket 스트림"},
            {"title": "4. 최신 프레임만 렌더링한다", "summary": "pull_latest_processed_frame는 큐에 쌓인 processed frame 중 가장 최신 것 하나만 소비하고 중간 프레임은 render 기준으로 건너뛴다.", "reason": "GUI가 늦어져도 화면이 최대한 최신 상태를 유지하게 만들기 위해서다.", "handoff": "렌더 대상 FramePacket과 skipped_render_frames 값"},
            {"title": "5. 화면용 overlay를 다시 계산한다", "summary": "update_detection_overlay에서 detection과 track을 RDI, RAI, 3D view 좌표로 바꿔 scatter와 레이블에 반영하고, display hysteresis로 짧은 confidence drop을 화면에서 완충한다.", "reason": "알고리즘 결과는 숫자 구조체라서, 사용자가 보려면 좌표 변환과 표시 필터가 한 번 더 필요하다. 다만 화면 hold는 실제 tracking 품질과 구분해 로그로 남겨야 한다.", "handoff": "화면에 표시되는 detection 점, confirmed/tentative track, display_held_track_count"},
            {"title": "6. render 로그와 종료 리포트를 맡는다", "summary": "log_render_snapshot으로 실제로 그려진 프레임만 기록하고, shutdown에서 SessionLogger를 통해 summary와 HTML 리포트 생성까지 이어진다.", "reason": "사용자 체감 성능과 알고리즘 처리 성능을 분리해서 보기 위해 render 로그가 별도로 필요하고, 세션 종료 후 자동 리포트도 중요해졌다.", "handoff": "render_frames.jsonl, event_log.jsonl, summary.json, ops_report.html, performance_report.html, trajectory_replay.html"},
        ],
        "blind_spots": [
            "이 파일이 처리한 모든 프레임을 그리는 것은 아니다. 화면은 최신 프레임만 소비하므로 render 로그만 보면 처리 파이프라인 자체를 오해할 수 있다.",
            "상수처럼 보이는 값 대부분은 코드 하드코딩이 아니라 세 개의 설정 파일에서 온다.",
            "사용자가 보는 track 수는 tracker의 confirmed/tentative 정책과 visualization 필터, display hysteresis가 한 번 더 걸린 결과다.",
            "SessionLogger가 남기는 메타데이터와 runtime_summary가 있어야 나중에 어떤 파라미터로 돌렸는지 추적할 수 있다.",
        ],
    },
    "live_motion_replay": {
        "summary": "저장된 logs/raw 캡처를 live viewer와 같은 UI로 다시 돌려 보고, x/y trajectory preview로 즉시 확인하는 replay 진입점이다.",
        "mentor": "rosbag처럼 같은 raw 입력을 다시 흘려 보내 알고리즘 변경 전후를 공정하게 비교하려고 만든 entrypoint다. 최근에는 replay 중에 heatmap보다 x/y 경로를 먼저 보여 주도록 바뀌었다.",
        "read_order": [
            "parse_args로 어떤 replay 옵션을 받는지 본다.",
            "resolve_capture_path로 세션 id와 절대 경로를 어떻게 해석하는지 본다.",
            "main에서 MotionViewer를 replay 모드로 어떻게 띄우는지 본다.",
        ],
        "landmarks": [
            ("parse_args", r"^def parse_args", "capture 경로와 재생 옵션을 파싱한다."),
            ("resolve_capture_path", r"^def resolve_capture_path", "logs/raw 세션 경로를 찾는다."),
            ("main", r"^def main", "MotionViewer를 replay 모드로 실행한다."),
        ],
        "simple_model": "이 파일은 replay 실행 스위치다. 저장된 raw capture를 읽어 기존 실시간 UI와 처리 파이프라인을 그대로 재사용하되, 결과는 x/y trajectory 중심으로 바로 확인하게 만든다.",
        "explainer_intro": "핵심은 새 UI를 따로 만드는 것이 아니라, live 경로와 같은 FramePacket 계약을 가진 replay source를 MotionViewer에 연결하고, replay 창에서는 x/y trajectory preview를 크게 보여 주는 것이다.",
        "explainer_steps": [
            {"title": "1. replay 인자를 읽는다", "summary": "캡처 디렉터리, 배속, 반복 여부, 자동 시작 여부를 받는다.", "reason": "같은 raw 입력을 여러 속도와 여러 조건으로 쉽게 재생해 봐야 회귀 비교가 쉬워진다.", "handoff": "CLI replay 옵션"},
            {"title": "2. capture 경로를 해석한다", "summary": "절대 경로, 프로젝트 상대 경로, logs/raw 세션 id shorthand를 모두 받아 실제 캡처 디렉터리로 바꾼다.", "reason": "사용자가 세션 id만 알아도 replay를 바로 열 수 있어야 실험 반복이 빠르다.", "handoff": "유효한 capture dir"},
            {"title": "3. 기존 MotionViewer를 replay 모드로 재사용한다", "summary": "input_mode=replay와 source_capture를 넘겨 같은 창에서 raw replay를 처리하고 x/y trajectory preview를 그린다.", "reason": "live와 replay가 다른 화면/다른 파이프라인을 쓰면 비교가 공정하지 않다.", "handoff": "replay UI 세션"},
            {"title": "4. replay 전용 리포트로 연결한다", "summary": "replay가 끝나면 trajectory_replay.html뿐 아니라 source capture와 재생 조건을 모은 replay_report.html도 생성한다.", "reason": "실험자가 raw 입력과 결과 링크를 바로 확인할 수 있어야 회귀 검증이 빨라진다.", "handoff": "replay_report.html"},
        ],
        "blind_spots": [
            "이 파일 자체는 처리 알고리즘을 새로 구현하지 않는다. 입력 소스만 live에서 replay로 바꿔 준다.",
            "replay 품질은 logs/raw 캡처가 실제로 저장돼 있어야만 확인할 수 있다.",
            "trajectory_replay.html과 달리 이 파일은 PyQt 실시간 UI에서 같은 pipeline을 다시 태우고, 종료 후 HTML trajectory report까지 바로 이어 준다.",
        ],
    },
    "real_time_process": {
        "simple_model": "이 파일은 조립 라인이다. live일 때는 UDP 패킷을 받아 한 프레임으로 조립하고 raw capture도 저장하며, replay일 때는 저장된 raw frame을 같은 FramePacket 구조로 다시 흘려 보낸다.",
        "explainer_intro": "입력은 live에서는 잘게 쪼개진 UDP 패킷이고, replay에서는 raw capture 파일이다. 출력은 둘 다 health와 detection과 track과 stage timing이 모두 들어 있는 FramePacket이다.",
        "explainer_steps": [
            {"title": "1. UDP 패킷을 검사하며 모은다", "summary": "UdpListener는 sequence와 byte count를 확인하며 payload를 모으고, 패킷 누락이나 순서 꼬임을 invalid 정보로 기록한다.", "reason": "레이더 입력이 깨졌는지 모르면 detection이 나빠진 원인이 알고리즘인지 네트워크인지 구분할 수 없다.", "handoff": "health 정보가 붙은 raw FramePacket"},
            {"title": "2. raw IQ를 radar cube로 바꾼다", "summary": "DataProcessor.run은 frame_to_radar_cube로 int16 IQ를 chirp/sample/channel 구조의 cube로 바꾼다.", "reason": "FFT와 detection은 의미 있는 축 구조를 가진 배열이 있어야 계산 가능하다.", "handoff": "radar cube"},
            {"title": "3. shared FFT 기반 DSP 결과를 만든다", "summary": "shared_range_doppler_fft를 한 번 계산하고, 그 결과를 RDI와 RAI 투영으로 나눠 쓴다.", "reason": "detection은 raw IQ가 아니라 에너지 맵 위에서 후보를 찾고, 중복 FFT를 줄여야 실시간성이 좋아진다.", "handoff": "RDI, RAI, shared FFT timing"},
            {"title": "4. detection과 tracking을 잇는다", "summary": "detect_targets로 후보를 만들고, invalid 정책에 따라 일부 프레임은 tracker 입력을 제한한다.", "reason": "입력이 불량한 프레임에서 새 track을 마구 태우면 추적 품질이 급격히 흔들린다.", "handoff": "tracker 입력 detection list, tracker policy"},
            {"title": "5. tracker를 갱신한다", "summary": "MultiTargetTracker.update를 호출해 confirmed와 tentative tracks를 갱신한다.", "reason": "프레임 단위 detection을 시간축 객체로 이어야 실시간 추적이 된다.", "handoff": "confirmed_tracks, tentative_tracks"},
            {"title": "6. processed 기준 로그와 stage timing을 남긴다", "summary": "log_processed_frame은 모든 처리 프레임을 JSONL로 남기고, 완성된 FramePacket과 stage_timings_ms를 processed queue에 넣는다.", "reason": "GUI가 느려도 알고리즘 자체 성능과 병목 위치는 별도로 측정해야 하므로 processed 로그가 필요하다.", "handoff": "processed_frames.jsonl, processed_frame_queue, stage_timings_ms"},
        ],
        "blind_spots": [
            "FramePacket은 단순 데이터 덩어리가 아니라, 한 프레임의 입력 무결성과 알고리즘 결과를 같이 들고 다니는 계약이다.",
            "invalid 프레임이라고 해서 항상 드롭하는 것은 아니다. 정책에 따라 no_birth 또는 full 처리로 갈린다.",
            "processed queue는 최신 것 위주로 유지되도록 설계되어 있어, UI는 중간 프레임을 모두 보지 못할 수 있다.",
            "이 파일 로그는 모든 처리 프레임 기준이고, 화면 로그는 별도다.",
            "이제는 capture_to_process_ms 하나만이 아니라 stage_timings_ms로 병목 위치까지 함께 봐야 한다.",
        ],
    },
    "radar_runtime": {
        "simple_model": "이 파일은 좌표계 번역기다. raw IQ를 radar cube, RDI, RAI, ROI 좌표계로 바꿔서 뒤 단계가 같은 언어를 쓰게 만든다.",
        "explainer_intro": "뒤 단계 detection과 tracking은 이 파일이 만든 배열 shape, 축 길이, 거리와 각도 해석을 그대로 믿고 움직인다. 최근에는 장착 방향 차이를 흡수하기 위해 lateral axis sign도 여기서 함께 해석한다.",
        "explainer_steps": [
            {"title": "1. cfg를 runtime config로 해석한다", "summary": "parse_runtime_config는 chirp, sample, tx/rx 수를 읽어 FFT 크기와 range/angle 축을 계산하고, 필요하면 좌우 축 부호도 함께 뒤집는다.", "reason": "입력 신호 길이와 공간 축 정의가 맞아야 이후 모든 bin 해석이 맞고, 장착 방향 차이도 이 계층에서 한 번에 정리하는 편이 안전하다.", "handoff": "RadarRuntimeConfig"},
            {"title": "2. 프레임 버퍼를 cube로 재배열한다", "summary": "frame_to_radar_cube는 raw IQ를 chirp, sample, virtual antenna 축으로 재구성한다.", "reason": "DSP 함수는 선형 버퍼가 아니라 의미 있는 축 구조를 가진 cube를 필요로 한다.", "handoff": "radar cube"},
            {"title": "3. 정지 clutter를 줄인다", "summary": "remove_static_clutter는 프레임 평균 성분을 빼서 움직이는 에너지를 더 눈에 띄게 만든다.", "reason": "정지 배경이 강하면 움직이는 대상이 묻혀 detection threshold가 흔들린다.", "handoff": "clutter가 줄어든 radar cube"},
            {"title": "4. 시각화와 검출용 맵을 만든다", "summary": "integrate_rdi_channels와 collapse_motion_rai가 detection에 쓸 range-doppler, range-angle 맵을 만든다.", "reason": "후단은 raw 복소수보다 압축된 에너지 맵에서 훨씬 안정적으로 후보를 찾는다.", "handoff": "RDI, motion RAI"},
            {"title": "5. 공간 ROI를 적용한다", "summary": "apply_cartesian_roi_to_rai는 lateral과 forward 범위를 기준으로 각도 축 일부만 남긴다.", "reason": "관심 영역 밖의 포인트를 early filter하면 false positive와 계산 낭비가 줄어든다.", "handoff": "ROI가 적용된 angle 정보"},
        ],
        "blind_spots": [
            "shape가 한 축이라도 어긋나면 detection과 tracking이 모두 연쇄적으로 틀어진다.",
            "angle axis는 단순 시각화 축이 아니라 DetectionCandidate의 angle_bin과 x/y 계산 기준이다.",
            "장착 방향 때문에 좌우가 반대로 보이면 report가 아니라 이 계층의 lateral_axis_sign부터 확인하는 편이 맞다.",
            "remove_static_clutter는 항상 좋은 것이 아니라 정지 대상까지 보고 싶다면 정보를 버릴 수도 있다.",
            "향후 Capon 같은 고급 angle estimator를 넣어도 axis와 antenna geometry 해석은 이 계층 이해가 먼저다.",
        ],
    },
    "detection": {
        "simple_model": "이 파일은 후보 심사관이다. RDI와 RAI에서 에너지 피크를 찾고, 각도와 공간 조건을 통과한 점만 DetectionCandidate로 만든다.",
        "explainer_intro": "한 프레임의 모든 에너지 피크를 다 객체로 취급하지 않고, 여러 단계 조건을 거쳐 tracker가 믿을 수 있는 후보만 남긴다. 최근에는 seed에서 coarse representative를 먼저 만들고, 가까운 candidate를 adaptive하게 미리 합친 뒤 살아남은 seed에만 range-angle local patch centroid를 적용해 body-center에 가까운 대표점을 만들려는 방향이 들어갔다.",
        "explainer_steps": [
            {"title": "1. RDI 관심 구간만 잘라 쓴다", "summary": "detect_targets는 min과 max range bin 안쪽만 사용하고 zero doppler 주변은 guard bin으로 비운다.", "reason": "정지 clutter와 관심 밖 거리 구간을 줄여야 moving target 후보가 더 또렷해진다.", "handoff": "정제된 rdi_work와 power_map"},
            {"title": "2. CFAR와 global floor를 합쳐 threshold를 만든다", "summary": "cfar_threshold_2d와 global_quantile이 함께 threshold_map을 만들고, local maxima만 후보로 남긴다.", "reason": "배경 대비 강한 점과 전체 분포 대비 강한 점을 동시에 요구해야 잡음에 덜 흔들린다.", "handoff": "candidate_indices"},
            {"title": "3. coarse representative를 만든다", "summary": "각 seed마다 RAI angle profile을 보고 ROI 안인지, local peak인지, angle contrast가 충분한지 확인한 뒤, 우선 range-angle 한 점에서 coarse x/y 후보를 만든다.", "reason": "비싼 body-center patch 계산을 모든 seed에 다 하지 않고, 먼저 살아남을 가능성이 있는 후보만 고르기 위해서다.", "handoff": "coarse candidate_pool"},
            {"title": "4. 가까운 coarse candidate를 미리 합친다", "summary": "_merge_candidate_pool은 range와 doppler와 Cartesian 거리를 함께 보며 같은 사람 안쪽으로 보이는 coarse candidate를 adaptive하게 미리 줄인다.", "reason": "DBSCAN 전에 한 사람 내부 중복 candidate를 먼저 줄여야 tracker가 여러 ID를 동시에 태우는 현상을 줄일 수 있고, 이후 local patch refine 비용도 줄일 수 있기 때문이다.", "handoff": "pre-merged coarse candidate_pool"},
            {"title": "5. 살아남은 후보만 body-center로 정밀 보정한다", "summary": "pre-merge를 통과한 후보에 대해서만 seed 주변 local patch에서 connected blob centroid를 다시 계산한다.", "reason": "body-center 쪽으로 대표점을 옮기는 계산은 중요하지만 가장 비싼 단계이므로 survivor에게만 적용하는 편이 실시간성에 유리하다.", "handoff": "refined candidate_pool"},
            {"title": "6. Cartesian 기준으로 묶는다", "summary": "_cluster_detection_candidates는 x와 y 좌표가 가까운 점을 dbscan_cluster로 묶는다.", "reason": "한 사람에서 range-doppler peak가 여러 개 나와도 detection 수를 사람이 이해할 수 있는 수로 줄여야 한다.", "handoff": "cluster summary"},
            {"title": "7. 클러스터를 DetectionCandidate로 바꾼다", "summary": "cluster 중심 x/y와 seed 점 score를 이용해 range_bin, angle_bin, doppler_bin을 다시 계산한다.", "reason": "tracker는 맵 픽셀 집합이 아니라, 좌표와 점수를 가진 후보 리스트를 필요로 한다.", "handoff": "DetectionCandidate list"},
            {"title": "8. 점수 순으로 정렬해 넘긴다", "summary": "최종 후보는 score, rdi_peak, rai_peak 기준으로 정렬되어 tracker로 전달된다.", "reason": "후단에서 상위 후보를 먼저 다루거나 로그를 볼 때 일관된 우선순위가 필요하다.", "handoff": "정렬된 detection candidate"},
        ],
        "blind_spots": [
            "DetectionCandidate 수는 raw peak 수와 다르다. clustering과 angle filter 때문에 줄어든 결과다.",
            "cfar_scale, global_quantile, angle_quantile은 서로 독립 파라미터가 아니라 함께 detection 민감도를 만든다.",
            "min_cartesian_separation_m은 range-doppler가 아니라 x와 y 공간에서 두 후보를 얼마나 떨어뜨릴지 정하는 값이다.",
            "최근에는 coarse candidate를 먼저 줄인 뒤 survivor에만 local patch centroid를 적용하도록 바뀌었어도, 아직 DetectionCandidate는 완전한 body-center 직접 측정이라기보다 강한 peak seed를 body-center 쪽으로 보정한 결과에 가깝다.",
            "adaptive eps band에 min_samples가 들어 있으면 전역 cluster_min_samples보다 그 값이 우선 적용된다.",
            "body_center_patch_bands는 range가 멀수록 patch를 넓게 보도록 해 주지만, 두 사람이 매우 가까우면 merge와 split 경계가 다시 민감해질 수 있다.",
            "candidate_merge_bands는 한 사람 내부 중복 후보를 줄이는 데 유리하지만, 두 사람이 매우 가까운 경우 과도하면 서로 합쳐질 위험도 있다.",
            "allow_strongest_fallback은 후보가 없을 때 가장 강한 점 하나를 강제로 살리는 안전장치다.",
            "지금 detection score는 확률값이 아니라 heuristic 조합값이므로 절대치보다 상대 비교로 보는 편이 안전하다.",
        ],
    },
    "dbscan_cluster": {
        "simple_model": "이 파일은 점 무리 해석기다. detection이 만든 point들을 사람 단위 cluster로 묶고, 밴드 경계 때문에 잘못 갈라진 cluster까지 다시 붙인다.",
        "explainer_intro": "질문에서 정리한 흐름이 큰 줄기는 맞다. 여기에 실제 코드가 하는 입력 정리, fallback range 계산, 경계 병합 조건, confidence 계산까지 더 보면 전체가 완성된다.",
        "explainer_steps": [
            {"title": "1. 입력 포인트를 깨끗하게 정리한다", "summary": "cluster_points는 각 point의 x, y를 float로 강제 변환하고, v와 score와 range도 유효하지 않으면 0으로 보정한다.", "reason": "DBSCAN은 거리 계산 기반이라 숫자형이 깨지면 전체 군집화가 바로 흔들린다.", "handoff": "clean point list"},
            {"title": "2. adaptive band 정의를 정규화한다", "summary": "normalize_adaptive_eps_bands는 list, tuple, JSON 문자열, compact 문자열 입력을 모두 받아 r_min, r_max, eps, min_samples가 정리된 band dict로 바꾼다.", "reason": "사용자가 밴드 설정을 여러 형식으로 줘도 clustering 본체는 항상 같은 구조를 보게 만들기 위해서다.", "handoff": "정렬되고 겹치지 않는 adaptive eps bands"},
            {"title": "3. 각 point가 어느 band에 속하는지 나눈다", "summary": "_effective_range가 point.range가 없거나 이상할 때는 hypot(x, y)로 range를 계산하고, _range_matches_band가 r_min과 r_max로 band를 판정한다.", "reason": "실제 point마다 다른 eps를 써야 가까운 거리와 먼 거리에서 군집 밀도 기준을 다르게 줄 수 있다.", "handoff": "band별 point list와 fallback_points"},
            {"title": "4. DBSCAN용 좌표를 만든다", "summary": "_build_feature_matrix는 기본적으로 (x, y)를 만들고, velocity feature를 켜면 (x, y, v * weight)로 확장한다.", "reason": "같은 위치에 가까워도 속도 차이가 큰 점은 분리하고 싶을 때 velocity를 제3축으로 쓰기 위해서다.", "handoff": "feature matrix"},
            {"title": "5. BFS 방식으로 cluster를 확장한다", "summary": "_dbscan_labels는 모든 점을 labels=-1로 시작하고, core point를 만나면 seeds 큐를 넓혀 가며 같은 cluster_id를 붙인다.", "reason": "DBSCAN의 핵심은 core point 주변의 밀집 연결성을 따라가며 point를 확장하는 것이다.", "handoff": "point별 cluster label, noise=-1"},
            {"title": "6. cluster를 요약 정보로 바꾼다", "summary": "_summarize_cluster_points는 점수 가중 평균으로 중심 x/y/v를 계산하고, spread_xy와 peak_score를 이용해 confidence를 만든다.", "reason": "후단 detection은 개별 point 목록보다 이 cluster가 어디에 있고 얼마나 믿을 만한가라는 요약값이 필요하다.", "handoff": "cluster summary dict"},
            {"title": "7. band 경계에서 갈라진 cluster를 다시 붙인다", "summary": "_merge_adaptive_boundary_clusters는 인접 band 경계를 공유하고 중심 거리와 경계 근접 조건을 만족하는 cluster 쌍을 다시 병합한다.", "reason": "원래 하나의 사람인데 band가 달라 eps가 달라져 인위적으로 쪼개지는 현상을 줄이기 위해서다.", "handoff": "최종 public cluster list"},
        ],
        "blind_spots": [
            "visited와 label은 다른 개념이다. visited=True인데 label=-1이면 검사는 했지만 아직 noise 상태라는 뜻이다.",
            "labels가 -1로 시작하는 것은 실패가 아니라 DBSCAN의 정상 초기화다. border point는 나중에 다른 core point의 이웃으로 편입될 수 있다.",
            "confidence는 확률이 아니라 size, spread, peak_score를 섞은 heuristic 점수다.",
            "adaptive band를 쓰더라도 어떤 band에도 안 들어간 point는 fallback_points 경로로 한 번 더 clustering된다.",
            "band 안에 min_samples가 명시되면 detection.py가 넘긴 전역 cluster_min_samples보다 그 값이 우선한다.",
            "경계 병합은 shared boundary, centroid distance, boundary proximity를 모두 통과해야 한다.",
        ],
        "landmarks": [
            ("normalize_adaptive_eps_bands", r"^def normalize_adaptive_eps_bands", "adaptive eps 설정을 정규화한다."),
            ("_range_matches_band", r"^def _range_matches_band", "point가 어느 band에 속하는지 검사한다."),
            ("_build_feature_matrix", r"^def _build_feature_matrix", "DBSCAN에 넣을 좌표를 만든다."),
            ("_dbscan_labels", r"^def _dbscan_labels", "BFS 방식으로 cluster label을 붙인다."),
            ("_summarize_cluster_points", r"^def _summarize_cluster_points", "cluster의 중심, spread, confidence를 계산한다."),
            ("_merge_adaptive_boundary_clusters", r"^def _merge_adaptive_boundary_clusters", "band 경계에서 갈라진 cluster를 병합한다."),
            ("cluster_points", r"^def cluster_points", "클러스터링 메인 함수다."),
        ],
        "read_order": [
            "cluster_points를 먼저 보고 입력 정리와 adaptive band 사용 여부가 어떻게 갈리는지 본다.",
            "normalize_adaptive_eps_bands와 _range_matches_band로 band 판정 규칙을 이해한다.",
            "_build_feature_matrix, _dbscan_labels, _summarize_cluster_points, _merge_adaptive_boundary_clusters 순으로 읽으면 전체가 자연스럽게 이어진다.",
        ],
    },
    "tracking": {
        "simple_model": "이 파일은 사람 ID 유지기다. 프레임마다 detection을 받아 기존 track과 잇고, tentative를 confirmed로 승격시키거나 오래된 track을 정리한다.",
        "explainer_intro": "detection은 한 프레임짜리 점 정보이고, tracking은 시간축 가설 관리다. 이 파일은 같은 사람이 다음 프레임에서도 같은 ID로 이어지게 만드는 정책을 모아 둔 곳이며, 최근에는 primary track 유지, lateral 안정화, track-conditioned local RAI remeasurement도 함께 맡는다.",
        "explainer_steps": [
            {"title": "1. tracker 정책을 초기화한다", "summary": "MultiTargetTracker.__init__은 process_var, measurement_var, gate, doppler 조건 등 추적 정책을 저장한다.", "reason": "추적 품질은 알고리즘보다 먼저 정책 숫자에 크게 좌우된다.", "handoff": "프레임마다 재사용되는 tracker 상태"},
            {"title": "2. 모든 기존 track을 예측한다", "summary": "Kalman filter로 현재 프레임 시점의 예상 위치와 속도를 계산한다.", "reason": "매칭은 현재 detection이 어디에 있을지 예상한 위치를 기준으로 해야 안정적이다.", "handoff": "예측된 track 상태"},
            {"title": "3. detection과 track 사이 비용을 만든다", "summary": "_associate는 거리와 doppler 차이를 비용으로 만들고, gate 밖 후보는 배제한다.", "reason": "가까워 보이는 detection이라도 속도나 상태가 너무 다르면 같은 사람으로 이어 붙이면 안 된다.", "handoff": "cost matrix와 유효 후보 쌍"},
            {"title": "4. 최적 매칭을 선택한다", "summary": "Hungarian assignment로 여러 detection과 여러 track의 최적 짝을 고른다.", "reason": "다중 타깃 상황에서 탐욕적으로 매칭하면 ID switch가 쉽게 난다.", "handoff": "matched, unmatched tracks와 detections"},
            {"title": "5. track 주변 local remeasurement를 적용한다", "summary": "매칭된 track은 detection x/y만 쓰지 않고, RAI patch에서 local centroid를 다시 계산한 뒤 기존 measurement와 제한적으로 섞는다.", "reason": "강한 반사점이 프레임마다 바뀌면 representative point가 몸 중심처럼 고정되지 않으므로, 기존 track 주변에서 한 번 더 재측정해 튐을 줄이기 위해서다.", "handoff": "remeasured measurement"},
            {"title": "6. primary track과 lateral 안정화를 적용한다", "summary": "대표 track을 일정 프레임 더 유지하고, 근처 새 birth를 억제하며, x 방향은 deadband와 smoothing으로 덜 흔들리게 만든다.", "reason": "원운동과 같은 패턴에서 좌우 지터와 근접 multi-ID split을 줄이기 위해서다.", "handoff": "stabilized track state"},
            {"title": "7. track을 갱신하거나 새로 만든다", "summary": "매칭된 track은 update되고, 남은 detection은 tentative track으로 태어나며, unmatched track은 misses가 증가한다.", "reason": "새 대상이 들어오거나 잠깐 가려지는 상황을 동시에 처리해야 하기 때문이다.", "handoff": "tentative, confirmed, lost 상태의 내부 track 리스트"},
            {"title": "8. 사용자용 TrackEstimate로 내보낸다", "summary": "최종적으로 confirmed와 tentative track을 export용 구조체로 바꿔 live_motion_viewer와 로그로 넘긴다.", "reason": "내부 Kalman 상태와 사용자에게 보여 줄 값은 다르므로 공개용 구조가 따로 필요하다.", "handoff": "TrackEstimate list"},
        ],
        "blind_spots": [
            "tentative track은 아직 확정된 사람이 아니다. confirm_hits 조건을 통과해야 confirmed가 된다.",
            "association gate 하나만 있는 것이 아니라 lost_gate_factor와 tentative_gate_factor로 상태별 gate가 다시 조절된다.",
            "doppler gating은 multi-target 상황에서 ID switch를 줄이는 중요한 축이다.",
            "confidence는 표시용 점수이기도 하지만 measurement noise scaling에도 간접적으로 영향을 준다.",
            "tracker가 좋아도 detection이 흔들리면 birth와 death가 잦아지므로 detection과 함께 봐야 한다.",
            "track-conditioned local remeasurement는 1차 보정이다. absolute ground truth나 카메라 기반 body-center calibration을 대체하지는 않는다.",
            "primary track 유지 로직과 display hysteresis는 continuity 체감을 돕지만, detection이 한 사람을 2~3개로 살리면 그것만으로는 완전히 해결되지 않는다.",
        ],
    },
    "runtime_settings": {
        "summary": "프로젝트 전반에서 공통으로 쓰는 설정을 static, runtime, tuning 세 층으로 나눠 로드하고 병합하는 설정 계층이다.",
        "mentor": "이 파일은 단순 JSON 로더가 아니라 설정 체계 설계 파일이다. 무엇을 거의 안 바꾸는지, 무엇을 세션마다 바꾸는지, 무엇을 튜닝하는지, 어떤 logging 토글을 켤지를 함께 결정한다. 최근에는 좌우 축 반전, raw capture/replay 경로, local remeasurement, display hysteresis 같은 실험 정책도 설정으로 흡수하게 됐다.",
        "before": "live_motion_static_settings.json / live_motion_runtime_settings.json / live_motion_tuning.json",
        "after": "live_motion_viewer.py, radar_runtime.py, real_time_process.py",
        "inputs": "세 개의 설정 JSON과 코드 기본값",
        "outputs": "병합된 settings dict, static/runtime/tuning snapshot, 절대 경로",
        "ops": "세 층 분리는 온보딩과 실험 반복 속도를 높인다. 팀원이 어디를 수정해야 할지 바로 알 수 있기 때문이다.",
        "read_order": [
            "DEFAULT_STATIC_SETTINGS, DEFAULT_RUNTIME_SETTINGS, DEFAULT_TUNING_SETTINGS를 먼저 훑어 역할이 어떻게 나뉘는지 본다.",
            "build_default_settings와 build_settings_snapshot으로 내부 표현을 어떻게 만드는지 확인한다.",
            "load_runtime_settings를 읽어 static -> runtime -> tuning 로딩 순서를 이해한다.",
        ],
        "roles": [
            ("기본값 계층화", "거의 안 바꾸는 값, 세션별 값, 튜닝값을 세 층으로 나눈다."),
            ("덮어쓰기 병합", "나중에 읽은 파일이 앞선 설정을 덮어쓰도록 깊은 병합을 수행한다."),
            ("실험 추적", "세션 로그에 static/runtime/tuning 스냅샷을 남길 수 있게 구조를 제공한다."),
        ],
        "landmarks": [
            ("DEFAULT_STATIC_SETTINGS", r"^DEFAULT_STATIC_SETTINGS\s*=", "거의 안 바꾸는 장비와 머신 기본값이다."),
            ("DEFAULT_RUNTIME_SETTINGS", r"^DEFAULT_RUNTIME_SETTINGS\s*=", "실행 세션에서 바꾸는 기본값이다."),
            ("DEFAULT_TUNING_SETTINGS", r"^DEFAULT_TUNING_SETTINGS\s*=", "최적화 대상 기본값이다."),
            ("build_default_settings", r"^def build_default_settings", "세 층 기본값을 하나의 dict로 합친다."),
            ("build_settings_snapshot", r"^def build_settings_snapshot", "특정 섹션만 떼어 static/runtime/tuning snapshot을 만든다."),
            ("load_runtime_settings", r"^def load_runtime_settings", "세 파일을 읽어 최종 settings를 만든다."),
            ("resolve_project_path", r"^def resolve_project_path", "프로젝트 루트 기준 절대 경로를 계산한다."),
        ],
        "simple_model": "이 파일은 설정 관리자다. 코드 기본값과 세 개의 JSON 파일을 합쳐 앱 전체가 같은 설정 사전을 보게 만든다.",
        "explainer_intro": "겹쳐 보이던 설정을 줄이기 위해, 이 파일은 static, runtime, tuning 세 층으로 설정을 명확하게 나눠 읽는다.",
        "explainer_steps": [
            {"title": "1. 코드 기본값을 층별로 정의한다", "summary": "static, runtime, tuning 기본값 dict를 따로 두고 build_default_settings에서 합친다.", "reason": "설정 파일이 빠져도 앱이 죽지 않게 하면서, 각 값의 역할을 코드에서 분리해 보여 주기 위해서다.", "handoff": "기본 settings dict"},
            {"title": "2. static 설정을 읽는다", "summary": "네트워크, DCA, 공간 뷰처럼 거의 안 바꾸는 값을 먼저 읽는다.", "reason": "하드웨어와 머신 성격 값은 튜닝 실험과 분리되어야 실수로 자주 건드리지 않게 된다.", "handoff": "static layer가 반영된 settings"},
            {"title": "3. runtime 설정을 읽는다", "summary": "cfg 경로, CLI 포트, logging 메타데이터, payload/snapshot/stage timing 토글 같은 세션 실행값을 덮어쓴다.", "reason": "같은 머신에서도 세션마다 포트와 실험 태그와 logging 수준은 바뀔 수 있기 때문이다.", "handoff": "runtime layer가 반영된 settings"},
            {"title": "4. tuning 설정을 마지막에 덮어쓴다", "summary": "ROI, detection, tracking, pipeline 같은 최적화용 값과 좌우 축 반전 같은 해석 설정을 tuning_path 기준으로 읽는다.", "reason": "실험할 때 가장 자주 바꾸는 값은 마지막 레이어에 두는 편이 이해하기 쉽고 안전하다.", "handoff": "최종 merged settings"},
            {"title": "5. snapshot과 절대 경로를 만든다", "summary": "static, runtime, tuning snapshot과 cfg 절대 경로를 만들어 앱과 세션 로그가 그대로 재사용하게 한다.", "reason": "나중에 어떤 설정으로 돌렸는지 회고할 수 있어야 실험 관리가 된다.", "handoff": "SETTINGS['static'], SETTINGS['runtime'], SETTINGS['tuning']"},
        ],
        "blind_spots": [
            "이 파일의 기본값은 사용자가 평소 수정하는 주 대상이 아니다. 실제 조정은 세 개의 JSON 파일에서 하는 것이 원칙이다.",
            "같은 키가 여러 층에 있으면 뒤에 읽은 파일 값이 최종 적용된다.",
            "settings_path 매개변수는 이전 구조 호환용 alias로만 남아 있다.",
            "deprecated live_motion_settings.json은 더 이상 로딩하지 않는다.",
        ],
    },
    "radar_config": {
        "simple_model": "이 파일은 UART 명령 전달자다. cfg 파일 내용을 센서에 밀어 넣고 시작과 정지 명령을 보내는 하드웨어 제어 계층이다.",
        "explainer_intro": "알고리즘이 아무리 좋아도 보드가 cfg를 제대로 적용하지 못하면 입력 자체가 달라진다. 그래서 이 파일은 실험 시작 조건을 실제 장비에 반영하는 역할을 한다.",
        "explainer_steps": [
            {"title": "1. 시리얼 연결을 연다", "summary": "SerialConfig가 COM 포트와 baudrate를 기반으로 센서 CLI 연결을 준비한다.", "reason": "cfg와 start와 stop 명령은 모두 CLI 포트를 통해 센서에 전달된다.", "handoff": "열린 시리얼 세션"},
            {"title": "2. CLI 응답을 읽고 검사한다", "summary": "_read_cli_response와 _has_cli_error가 센서 응답을 수집하고 에러 문자열을 검사한다.", "reason": "장비 설정 실패를 무시하면 이후 문제를 신호 처리 탓으로 오해하기 쉽다.", "handoff": "응답 라인과 에러 여부"},
            {"title": "3. cfg 파일을 줄 단위로 보낸다", "summary": "SendConfig는 주석과 빈 줄을 제외하고 cfg 명령을 순차적으로 전송한다.", "reason": "레이더 설정은 한 번에 JSON을 보내는 것이 아니라 CLI 명령 시퀀스이기 때문이다.", "handoff": "센서에 적용된 profile과 chirp와 frame 설정"},
            {"title": "4. 센서를 시작, 정지, 해제한다", "summary": "StartRadar, StopRadar, DisconnectRadar가 실험 생명주기를 마무리한다.", "reason": "실험 사이클이 반복될수록 장비 정리 루틴이 안정적이어야 포트 충돌과 상태 꼬임이 줄어든다.", "handoff": "정상 시작 또는 정지된 하드웨어 상태"},
        ],
        "blind_spots": [
            "이 파일은 계산 결과보다 side effect가 중요한 파일이다. 성공 여부는 센서 상태 변화와 응답으로 판단해야 한다.",
            "cfg 전송 순서와 중간 응답 확인이 중요해서, 단순 파일 읽기보다 장비 프로토콜 코드로 보는 편이 맞다.",
            "COM 포트 점유 문제는 코드 버그처럼 보이지만 실제로는 OS나 드라이버 이슈일 수 있다.",
            "지금은 print 중심이 남아 있어, 현장 장애 분석용으로는 structured logging 전환 여지가 있다.",
        ],
    },
    "DSP": {
        "simple_model": "이 파일은 기초 FFT 엔진이다. radar cube를 공통 range-doppler FFT로 바꾼 뒤 RDI와 RAI로 갈라서 후단 검출이 쓸 스펙트럼을 만든다.",
        "explainer_intro": "현재 프로젝트의 기본 angle estimator는 FFT 기반이므로, 이 파일에서 나오는 맵 품질과 FFT 비용이 detection 품질과 latency의 바닥을 결정한다.",
        "explainer_steps": [
            {"title": "1. window를 캐시하고 broadcasting으로 곱한다", "summary": "_cached_range_doppler_window가 Hann window를 재사용하고, shared_range_doppler_fft가 채널 전체에 broadcasting으로 적용한다.", "reason": "프레임마다 같은 window를 다시 만들지 않아야 CPU 낭비가 줄어든다.", "handoff": "windowed radar cube"},
            {"title": "2. 공통 range-doppler FFT를 한 번 계산한다", "summary": "shared_range_doppler_fft는 chirp와 sample 축 2D FFT를 한 번만 수행한다.", "reason": "움직임과 거리 정보는 먼저 range-doppler 평면에서 분리하고, 이 결과를 RDI와 RAI가 공유하도록 만드는 것이 현재 최적화 포인트다.", "handoff": "shared FFT cube"},
            {"title": "3. RDI와 RAI 투영으로 나눈다", "summary": "range_doppler_from_fft는 공통 FFT를 RDI로, range_angle_from_fft는 같은 FFT를 angle 축 변환으로 RAI로 바꾼다.", "reason": "예전처럼 큰 FFT를 두 번 반복하지 않고 후단 map만 갈라서 쓰기 위해서다.", "handoff": "RDI cube, RAI cube"},
            {"title": "4. wrapper로 기존 호출 호환성을 유지한다", "summary": "Range_Doppler와 Range_Angle은 내부적으로 shared path를 쓰면서도 기존 호출부 인터페이스는 유지한다.", "reason": "호출부를 전부 깨지 않으면서 최적화를 단계적으로 넣기 위해서다.", "handoff": "호환 가능한 RDI/RAI API"},
        ],
        "blind_spots": [
            "이 파일은 고급 beamforming이 아니라 baseline FFT angle estimator다.",
            "mode에 따라 반환 shape와 타입이 달라지므로, 호출부가 어떤 모드를 기대하는지 항상 같이 봐야 한다.",
            "지금 핵심은 FFT를 한 번만 계산하는 shared path이며, wrapper 이름이 남아 있다고 해서 예전처럼 매번 중복 FFT를 하는 것은 아니다.",
            "축 순서와 transpose와 flip을 놓치면 화면은 그럴듯해 보여도 좌표 해석이 틀릴 수 있다.",
        ],
    },
    "app_layout": {
        "simple_model": "이 파일은 빈 화면 골격이다. 로직은 거의 없고, 상위 컨트롤러가 붙잡아 쓸 위젯 구조를 만들어 준다.",
        "explainer_intro": "초보자가 보기엔 코드 양이 적어 중요하지 않아 보일 수 있지만, 어떤 widget 이름을 상위 코드가 참조하는지 여기서 결정된다.",
        "explainer_steps": [
            {"title": "1. 메인 창과 패널을 만든다", "summary": "setupUi는 QMainWindow 안에 central widget, plot 영역, 버튼, 라벨을 배치한다.", "reason": "실시간 앱은 먼저 표시 영역과 제어 버튼 골격이 있어야 한다.", "handoff": "위젯 트리"},
            {"title": "2. objectName을 고정한다", "summary": "각 위젯의 이름이 지정되어 상위 코드가 해당 객체를 찾아 쓸 수 있게 된다.", "reason": "UI 파일과 로직 파일이 분리되어 있을 때 objectName이 사실상 계약 역할을 한다.", "handoff": "live_motion_viewer가 참조할 UI 식별자"},
            {"title": "3. 표시 텍스트를 채운다", "summary": "retranslateUi가 버튼과 레이블 텍스트를 최종 세팅한다.", "reason": "다국어 대응이나 텍스트 변경도 구조와 분리해 두기 위해서다.", "handoff": "사용자에게 보이는 기본 UI 텍스트"},
        ],
        "blind_spots": [
            "로직이 적다고 중요하지 않은 파일은 아니다. objectName이 바뀌면 상위 컨트롤러가 바로 깨질 수 있다.",
            "Qt Designer generated file 성격이라 직접 수정한 내용은 재생성 때 덮일 수 있다.",
            "이 파일은 데이터 처리 코드가 아니라 UI 계약 파일로 읽는 편이 좋다.",
            "화면 문제를 디버깅할 때는 이 파일과 live_motion_viewer.py를 같이 봐야 한다.",
        ],
    },
    "legacy_xwr1843_app": {
        "simple_model": "이 파일은 예전 일체형 데모다. 지금 구조가 왜 분리되었는지 보여 주는 비교 대상이다.",
        "explainer_intro": "현재 메인 경로는 아니지만, 프로젝트가 어떻게 발전해 왔는지 이해할 때 좋은 대비군이다.",
        "explainer_steps": [
            {"title": "1. 장비 명령과 UI가 한곳에 있다", "summary": "send_cmd가 DCA 명령 패킷을 직접 만들고, 같은 파일에서 UI 갱신도 처리한다.", "reason": "초기 PoC에서는 빠르게 동작시키는 것이 우선이라 책임이 한 파일에 몰리기 쉽다.", "handoff": "단일 파일 안의 전역 상태"},
            {"title": "2. 처리 워커를 직접 띄운다", "summary": "UdpListener와 DataProcessor를 직접 가져와 큐를 연결한다.", "reason": "기본 데모를 빠르게 보기에는 단순하지만, 구조 확장성은 떨어진다.", "handoff": "실시간 RDI와 RAI 데이터"},
            {"title": "3. plot과 update_figure로 화면을 갱신한다", "summary": "최신 데이터를 pyqtgraph 이미지에 직접 올리는 단순 루프 구조를 쓴다.", "reason": "초기 데모는 시각화 확인이 1차 목표였기 때문이다.", "handoff": "실시간 플롯"},
            {"title": "4. 현재 구조와 비교 자료가 된다", "summary": "로그 분리, 세션 메타, processed와 render 구분이 없다는 점이 현재 구조와 가장 큰 차이다.", "reason": "새 구조의 가치가 무엇인지 설명할 때 레거시와 비교하면 이해가 빠르다.", "handoff": "아키텍처 비교 기준"},
        ],
        "blind_spots": [
            "이 파일은 현재 추천 entrypoint가 아니다. 참고용과 비교용으로 읽는 편이 맞다.",
            "한 파일에 제어와 렌더와 워커 관리가 같이 있어, 구조적 단순함과 유지보수 어려움이 동시에 보인다.",
            "현재 문서와 리포트 체계는 이 파일이 아니라 live_motion_viewer 경로 기준으로 발전했다.",
            "새 기능을 붙일 땐 이 파일보다 현재 앱 구조를 기준으로 생각하는 편이 안전하다.",
        ],
    },
    "session_report": {
        "simple_model": "이 파일은 세션 통계 압축기다. JSONL 로그 여러 개를 읽어 사람이 바로 비교할 수 있는 summary.json 하나로 요약하고, 그 안에 운영 점수와 성능 KPI, 그리고 눈으로 보는 경로 품질 지표까지 함께 넣는다.",
        "explainer_intro": "로그가 남는 것과 비교 가능한 숫자가 생기는 것은 다르다. 이 파일은 raw log를 실험 판단에 쓸 수 있는 통계로 바꾸고, render 지연과 compute 예산과 continuity뿐 아니라 path geometry까지 한 스키마로 묶는 역할을 한다.",
        "explainer_steps": [
            {"title": "1. 세션 경로와 JSONL을 읽는다", "summary": "_resolve_session_dir, _load_json, _load_jsonl이 세션 폴더와 로그 파일을 안전하게 읽는다.", "reason": "옛 세션이나 일부 로그가 없는 세션도 최대한 읽혀야 실험 기록을 잃지 않는다.", "handoff": "processed_records, render_records, session_meta"},
            {"title": "2. 숫자 집계 함수를 준비한다", "summary": "_quantile, _safe_rate, _summarize_numeric가 mean과 p50과 p95와 rate 계산을 맡는다.", "reason": "세션마다 같은 스키마로 통계를 만들어야 before와 after 비교가 안정적이다.", "handoff": "재사용 가능한 통계 dict"},
            {"title": "3. processed와 render를 분리 집계한다", "summary": "build_summary는 processed_frames와 render_frames를 따로 세어 latency와 track count를 각각 계산한다.", "reason": "알고리즘 처리 성능과 사용자 체감 렌더 성능을 같은 값으로 섞으면 원인 분석이 어려워진다.", "handoff": "processed summary, render summary"},
            {"title": "4. stage timing과 환경 정보를 합친다", "summary": "_summarize_stage_timings와 _build_system_summary가 slow stage와 system snapshot을 summary 안에 넣는다.", "reason": "같은 코드인데 성능이 흔들릴 때 stage 병목과 환경 요인을 함께 봐야 정확하다.", "handoff": "diagnostics, system summary"},
            {"title": "5. 성능 KPI와 운영 점수를 함께 만든다", "summary": "_build_performance_summary가 frame budget, throughput, compute utilization, jitter, continuity, geometry/path quality를 정리하고, operational_assessment가 운영 점수와 권고를 만든다.", "reason": "현업에서는 평균 latency 하나보다 예산 대비 사용률과 continuity와 운영 수준, 그리고 사람이 보기 좋은 경로 모양까지 같이 보는 편이 설명력이 크다.", "handoff": "performance, assessment"},
            {"title": "6. summary.json으로 저장한다", "summary": "main은 최종 summary dict를 파일로 써서 다음 비교 단계와 HTML 리포트 단계에 넘긴다.", "reason": "실험 비교는 raw JSONL이 아니라 요약 스키마 기준으로 굴리는 편이 안정적이다.", "handoff": "summary.json (performance + assessment 포함)"},
        ],
        "blind_spots": [
            "render 로그가 없으면 legacy status_log.jsonl을 fallback으로 읽는다.",
            "이 파일이 계산하는 success rate는 label 없는 운영 지표이지 정답 기반 accuracy 지표는 아니다.",
            "processed와 render를 분리해 보는 것이 이 파일의 가장 중요한 가치다.",
            "최근에는 summary.performance가 추가되어 같은 summary.json 안에서 throughput, compute budget, jitter, continuity, geometry/path quality를 따로 읽을 수 있다.",
            "summary schema가 바뀌면 session_compare와 HTML 리포트도 함께 손봐야 한다.",
        ],
    },
    "session_compare": {
        "simple_model": "이 파일은 A/B 판정기다. 두 summary.json을 읽어 무엇이 좋아졌고 무엇이 나빠졌는지 방향까지 붙여 준다. 최근에는 운영 점수뿐 아니라 throughput, jitter, continuity, path geometry KPI도 기본 비교 항목에 들어간다.",
        "explainer_intro": "실험이 많아질수록 숫자만 나열하는 것보다, 어떤 지표는 낮을수록 좋고 어떤 지표는 높을수록 좋은지 자동으로 판정해 주는 도구가 필요하다. 지금은 latency만이 아니라 render fps, compute utilization, lead switch, path cleanliness 같은 지표도 함께 본다.",
        "explainer_steps": [
            {"title": "1. 비교할 지표 목록을 정의한다", "summary": "METRICS는 어떤 key를 비교할지와 lower 또는 higher 방향을 미리 정해 둔다. 최근에는 operational score뿐 아니라 render vs expected ratio, compute utilization, render jitter, lead switch, path cleanliness도 이 목록에 포함된다.", "reason": "같은 delta라도 latency와 success rate는 해석 방향이 반대이고, 운영 점수 변화와 성능 KPI, 경로 기하 품질 변화를 함께 봐야 하기 때문이다.", "handoff": "비교 대상 metric spec"},
            {"title": "2. before와 after summary를 읽는다", "summary": "_load_summary가 디렉터리 또는 summary.json 입력을 받아 실제 JSON을 로드한다.", "reason": "CLI 사용성을 높이고 자동화 스크립트에서 재사용하기 쉽게 하기 위해서다.", "handoff": "before_summary, after_summary"},
            {"title": "3. 값과 변화량을 계산한다", "summary": "_nested_get, _percent_change, _judgement가 값 추출, delta, 개선과 회귀 판정을 수행한다.", "reason": "요약 스키마가 중첩 dict 구조라 dotted key 접근과 방향 해석이 필요하다.", "handoff": "metric별 comparison row"},
            {"title": "4. 비교 결과를 저장하고 출력한다", "summary": "build_comparison과 main이 comparison json을 쓰고 콘솔에 핵심 결과를 표시한다.", "reason": "사람이 바로 확인하는 용도와 후속 자동화가 읽는 용도를 동시에 만족해야 한다.", "handoff": "comparison_vs_*.json"},
        ],
        "blind_spots": [
            "0으로 나누는 percent_change는 None으로 처리한다.",
            "지표가 없거나 None이면 improved와 regressed 대신 n/a가 나온다.",
            "이 파일은 아직 threshold 기반 pass와 fail보다 방향 판정 중심이다.",
            "좋아졌다는 판단은 METRICS에 적힌 direction 정의에 전적으로 달려 있다.",
        ],
    },
    "read_binfile": {
        "simple_model": "이 파일은 오프라인 입력 복원기다. mmWave Studio .bin 파일을 complex radar cube로 되돌려 replay와 offline 분석에 쓰게 만든다.",
        "explainer_intro": "실시간 비교는 장면이 조금만 달라도 흔들리기 쉬우므로, 결국 같은 raw 입력을 다시 돌리는 replay 경로가 필요하다. 그 시작점이 이 파일이다.",
        "explainer_steps": [
            {"title": "1. 필요하면 UDP header를 제거한다", "summary": "remove_header는 Studio capture에 붙은 헤더 샘플을 삭제해 순수 ADC 데이터만 남긴다.", "reason": "헤더가 남아 있으면 이후 reshape가 전부 틀어지기 때문이다.", "handoff": "header가 제거된 int16 stream"},
            {"title": "2. int16를 complex IQ로 묶는다", "summary": "read_bin_file은 실수와 허수 채널을 묶어 복소수 샘플로 만든다.", "reason": "레이더 DSP는 복소수 baseband 데이터를 전제로 한다.", "handoff": "complex sample array"},
            {"title": "3. 장비 모드에 맞게 reshape한다", "summary": "mode와 tx와 rx 수에 따라 frame, chirp, sample, channel 축으로 재배열한다.", "reason": "XWR 계열마다 raw 저장 순서가 달라서 하나의 reshape 규칙으로는 맞지 않기 때문이다.", "handoff": "frame x chirp x sample x channel cube"},
            {"title": "4. DSP와 replay 경로로 넘긴다", "summary": "복원된 cube는 DSP baseline이나 future replay pipeline의 입력으로 재사용될 수 있다.", "reason": "같은 입력으로 전후 알고리즘을 비교해야 의미 있는 A/B가 되기 때문이다.", "handoff": "offline radar cube"},
        ],
        "blind_spots": [
            "mode, tx_num, rx_num, sample 수가 하나라도 틀리면 output shape가 완전히 어긋난다.",
            "header 제거 여부를 잘못 선택하면 값 자체가 맞아 보여도 축이 틀어질 수 있다.",
            "이 파일은 실시간 파이프라인이 아니라 offline와 replay 입력 계층으로 읽는 편이 맞다.",
            "현재 앱의 기본 경로는 live이지만, 재현 가능한 실험은 결국 이 파일 기반 replay가 필요하다.",
        ],
    },
}
